version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-maven-cache-{{ checksum "pom.xml" }}
      - run:
          name: Build with Maven
          command: |
            chmod +x ./mvnw
            ./mvnw clean package -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: v1-maven-cache-{{ checksum "pom.xml" }}
      - run:
          name: Build Docker image
          command: |
            docker build -t nassar001/project:latest .
            docker tag nassar001/project:latest nassar001/project:${CIRCLE_SHA1}
      - run:
          name: Push to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push nassar001/project:latest
            docker push nassar001/project:${CIRCLE_SHA1}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main
